
- name: Create data path
  ansible.builtin.file:
    path: "{{ discordbot_data_path }}"
    state: directory

- name: Upload default intents
  ansible.builtin.copy:
    src: default-intents.json
    dest: "{{ discordbot_data_path }}/default-intents.json"

- name: Pull Docker image
  community.docker.docker_image:
    name: "{{ discordbot_image }}"
    source: pull
    force_source: true

- name: Template config files
  ansible.builtin.template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  loop:
    - {src: docker-compose.tpl.yml, dest: "{{ discordbot_data_path }}-compose.yml"}
    - {src: redbot-config.tpl.json, dest: "{{ discordbot_data_path }}/redbot-config.json"}
    - {src: discordbot-config.tpl.json, dest: "{{ discordbot_data_path }}/discordbot-config.json"}