name: wm-management-api

on:
  push:
    paths:
      - .github/workflows/wm-management-api.yml
      - wm-management-api/**
    branches:
      - main
    tags:
      - 'releases/wm-management-api/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker tag
        id: docker_tag
        run: echo ::set-output name=DOCKER_TAG::${GITHUB_REF/refs\/tags\/releases\/wm-management-api\/v/}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push
        uses: docker/build-push-action@v2
        if: contains(github.ref, 'refs/tags')
        with:
          context: ./wm-management-api
          file: ./wm-management-api/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wm-management-api:${{ steps.docker_tag.outputs.DOCKER_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push
        uses: docker/build-push-action@v2
        if: contains(github.ref, 'refs/heads') && !contains(github.ref, 'main')
        with:
          context: ./wm-management-api
          file: ./wm-management-api/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wm-management-api:${GITHUB_REF/refs\/heads\//}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push
        uses: docker/build-push-action@v2
        if: contains(github.ref, 'main')
        with:
          context: ./wm-management-api
          file: ./wm-management-api/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wm-management-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
